name: Processor for Forms submission events

on:
  repository_dispatch:
    types: [form-data-received]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Form data processor action
        id: data-processor
        uses: hegupta-adbe/form-data-processor@master
        with:
          azure-client-id: ${{ secrets.AZURE_CLIENT_ID }}
          azure-client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          azure-resource: ${{ secrets.AZURE_RESOURCE }}
      - name: Get the outpus
        run: echo "The result of processing was ${{ steps.hello.data-processor.processing-result }}"
